# argocd-git-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: github-infra-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository # 👈 O pulo do gato pro ArgoCD reconhecer
type: Opaque
stringData:
  type: git
  url: https://github.com/flima835/infra-wishlist-chart.git
  username: flima835
  password: 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
